name: Auto Deploy to Vercel

on:
  push:
    branches:
      - main
      - dev
      - qa

jobs:
  deploy-landing:
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.message, '[skip landing]') == false
    steps:
      - uses: actions/checkout@v3

      - name: Check for landing changes
        id: landing_changes
        run: |
          git fetch origin ${{ github.ref_name }} --depth=2
          if git diff --name-only HEAD~1 HEAD | grep "^apps/landing/"; then
            echo "changed=true" >> $GITHUB_OUTPUT
          else
            echo "changed=false" >> $GITHUB_OUTPUT
          fi

      - name: Trigger landing deploy
        if: steps.landing_changes.outputs.changed == 'true'
        run: |
          if [ "${{ github.ref_name }}" = "main" ]; then
            curl -X POST "${{ secrets.VERCEL_DEPLOY_LANDING_MAIN }}"
          elif [ "${{ github.ref_name }}" = "dev" ]; then
            curl -X POST "${{ secrets.VERCEL_DEPLOY_LANDING_DEV }}"
          elif [ "${{ github.ref_name }}" = "qa" ]; then
            curl -X POST "${{ secrets.VERCEL_DEPLOY_LANDING_QA }}"
          fi

  deploy-calendar:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Check for calendar changes
        id: calendar_changes
        run: |
          git fetch origin ${{ github.ref_name }} --depth=2
          if git diff --name-only HEAD~1 HEAD | grep "^apps/calendar/"; then
            echo "changed=true" >> $GITHUB_OUTPUT
          else
            echo "changed=false" >> $GITHUB_OUTPUT
          fi

      - name: Trigger calendar deploy
        if: steps.calendar_changes.outputs.changed == 'true'
        run: |
          if [ "${{ github.ref_name }}" = "main" ]; then
            curl -X POST "${{ secrets.VERCEL_DEPLOY_CALENDAR_MAIN }}"
          elif [ "${{ github.ref_name }}" = "dev" ]; then
            curl -X POST "${{ secrets.VERCEL_DEPLOY_CALENDAR_DEV }}"
          elif [ "${{ github.ref_name }}" = "qa" ]; then
            curl -X POST "${{ secrets.VERCEL_DEPLOY_CALENDAR_QA }}"
          fi
