name: Deploy to Vercel

on:
  push:
    branches:
      - main

jobs:
  deploy-landing:
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.message, '[skip landing]') == false
    steps:
      - uses: actions/checkout@v3
      - name: Check for landing changes
        id: landing_changes
        run: |
          if git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep "^apps/landing/"; then
            echo "changed=true" >> $GITHUB_OUTPUT
          else
            echo "changed=false" >> $GITHUB_OUTPUT 
          fi
      - name: Trigger landing deploy
        if: steps.landing_changes.outputs.changed == 'true'
        run: curl -X POST "https://api.vercel.com/v1/integrations/deploy/prj_tJDcVWcwFO423izSOCkuYwnIah8m/L4rDDXLFEV"

  deploy-calendar:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Check for calendar changes
        id: calendar_changes
        run: |
          if git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep "^apps/calendar/"; then
            echo "changed=true" >> $GITHUB_OUTPUT
          else
            echo "changed=false" >> $GITHUB_OUTPUT
          fi
      - name: Trigger calendar deploy
        if: steps.calendar_changes.outputs.changed == 'true'
        run: curl -X POST "https://api.vercel.com/v1/integrations/deploy/prj_yzMHglFe4LmIKtazxACHgfphnJzs/tmtVy4XPGO"
