name: Auto Deploy to Vercel

on:
  push:
    branches:
      - main
      - dev

jobs:
  deploy-landing:
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.message, '[skip landing]') == false
    steps:
      - uses: actions/checkout@v3

      - name: Check for landing changes
        id: landing_changes
        run: |
          git fetch origin ${{ github.ref_name }} --depth=2
          if git diff --name-only HEAD~1 HEAD | grep "^apps/landing/"; then
            echo "changed=true" >> $GITHUB_OUTPUT
          else
            echo "changed=false" >> $GITHUB_OUTPUT
          fi

      - name: Create Vercel config (landing)
        if: steps.landing_changes.outputs.changed == 'true'
        run: |
          mkdir -p apps/landing/.vercel
          echo "{\"orgId\":\"${{ secrets.VERCEL_ORG_ID }}\",\"projectId\":\"${{ secrets.VERCEL_PROJECT_ID_LANDING }}\"}" > apps/landing/.vercel/project.json

      - name: Build landing
        if: steps.landing_changes.outputs.changed == 'true'
        run: |
          cd apps/landing
          npm ci
          npx vercel build --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy landing
        if: steps.landing_changes.outputs.changed == 'true'
        run: |
          cd apps/landing
          if [ "${{ github.ref_name }}" = "main" ]; then
            npx vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }} --prod
          else
            npx vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }}
          fi

  deploy-calendar:
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.message, '[skip calendar]') == false
    steps:
      - uses: actions/checkout@v3

      - name: Check for calendar changes
        id: calendar_changes
        run: |
          git fetch origin ${{ github.ref_name }} --depth=2
          if git diff --name-only HEAD~1 HEAD | grep "^apps/calendar/"; then
            echo "changed=true" >> $GITHUB_OUTPUT
          else
            echo "changed=false" >> $GITHUB_OUTPUT
          fi

      - name: Create Vercel config (calendar)
        if: steps.calendar_changes.outputs.changed == 'true'
        run: |
          mkdir -p apps/calendar/.vercel
          echo "{\"orgId\":\"${{ secrets.VERCEL_ORG_ID }}\",\"projectId\":\"${{ secrets.VERCEL_PROJECT_ID_CALENDAR }}\"}" > apps/calendar/.vercel/project.json

      - name: Build calendar
        if: steps.calendar_changes.outputs.changed == 'true'
        run: |
          cd apps/calendar
          npm ci
          npx vercel build --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy calendar
        if: steps.calendar_changes.outputs.changed == 'true'
        run: |
          cd apps/calendar
          if [ "${{ github.ref_name }}" = "main" ]; then
            npx vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }} --prod
          else
            npx vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }}
          fi
