name: Manual Deploy to Vercel

on:
  workflow_dispatch:
    inputs:
      app:
        description: 'target (landing / calendar)'
        required: true
        type: choice
        options:
          - landing
          - calendar
      branch:
        description: 'branch (main/dev)'
        default: 'main'
        required: true
        type: choice
        options:
          - main
          - dev

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Deploy landing
        if: ${{ github.event.inputs.app == 'landing' }}
        shell: bash
        working-directory: apps/landing
        run: |
          npm ci
          mkdir -p .vercel
          printf '{"orgId":"%s","projectId":"%s"}' "${{ secrets.VERCEL_ORG_ID }}" "${{ secrets.VERCEL_PROJECT_ID_LANDING }}" > .vercel/project.json
          test -f .vercel/project.json || { echo "project.json missing"; exit 1; }
          npx vercel build --token=${{ secrets.VERCEL_TOKEN }}
          if [ "${{ github.event.inputs.branch }}" = "main" ]; then
            npx vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }} --prod
          else
            npx vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }}
          fi

      - name: Deploy calendar
        if: ${{ github.event.inputs.app == 'calendar' }}
        shell: bash
        working-directory: apps/calendar
        run: |
          npm ci
          mkdir -p .vercel
          printf '{"orgId":"%s","projectId":"%s"}' "${{ secrets.VERCEL_ORG_ID }}" "${{ secrets.VERCEL_PROJECT_ID_CALENDAR }}" > .vercel/project.json
          test -f .vercel/project.json || { echo "project.json missing"; exit 1; }
          npx vercel build --token=${{ secrets.VERCEL_TOKEN }}
          if [ "${{ github.event.inputs.branch }}" = "main" ]; then
            npx vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }} --prod
          else
            npx vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }}
          fi
