name: Manual Deploy to Vercel

on:
  workflow_dispatch:
    inputs:
      app:
        description: 'target (landing / calendar)'
        required: true
        type: choice
        options:
          - landing
          - calendar
      branch:
        description: 'branch (main/dev)'
        default: 'main'
        required: true
        type: choice
        options:
          - main
          - dev

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Deploy landing
        if: ${{ github.event.inputs.app == 'landing' }}
        run: |
          cd apps/landing
          npm ci
          npm run build
          if [ "${{ github.event.inputs.branch }}" = "main" ]; then
            npx vercel deploy --prebuilt \
              --token=${{ secrets.VERCEL_TOKEN_LANDING }} \
              --org ${{ secrets.VERCEL_ORG_ID }} \
              --project ${{ secrets.VERCEL_PROJECT_ID_LANDING }} \
              --prod
          else
            npx vercel deploy --prebuilt \
              --token=${{ secrets.VERCEL_TOKEN_LANDING }} \
              --org ${{ secrets.VERCEL_ORG_ID }} \
              --project ${{ secrets.VERCEL_PROJECT_ID_LANDING }}
          fi

      - name: Deploy calendar
        if: ${{ github.event.inputs.app == 'calendar' }}
        run: |
          cd apps/calendar
          npm ci
          npm run build
          if [ "${{ github.event.inputs.branch }}" = "main" ]; then
            npx vercel deploy --prebuilt \
              --token=${{ secrets.VERCEL_TOKEN_CALENDAR }} \
              --org ${{ secrets.VERCEL_ORG_ID }} \
              --project ${{ secrets.VERCEL_PROJECT_ID_CALENDAR }} \
              --prod
          else
            npx vercel deploy --prebuilt \
              --token=${{ secrets.VERCEL_TOKEN_CALENDAR }} \
              --org ${{ secrets.VERCEL_ORG_ID }} \
              --project ${{ secrets.VERCEL_PROJECT_ID_CALENDAR }}
          fi
