name: Manual Deploy to Vercel

on:
  workflow_dispatch:
    inputs:
      app:
        description: 'target (landing / calendar)'
        required: true
        type: choice
        options:
          - landing
          - calendar
      branch:
        description: 'branch (main/dev/qa)'
        default: 'main'
        required: true
        type: choice
        options:
          - main
          - dev
          - qa

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Deploy landing
        if: ${{ github.event.inputs.app == 'landing' }}
        run: |
          if [ "${{ github.event.inputs.branch }}" = "main" ]; then
            curl -X POST "${{ secrets.VERCEL_DEPLOY_LANDING_MAIN }}"
          elif [ "${{ github.event.inputs.branch }}" = "dev" ]; then
            curl -X POST "${{ secrets.VERCEL_DEPLOY_LANDING_DEV }}"
          elif [ "${{ github.event.inputs.branch }}" = "qa" ]; then
            curl -X POST "${{ secrets.VERCEL_DEPLOY_LANDING_QA }}"
          fi

      - name: Deploy calendar
        if: ${{ github.event.inputs.app == 'calendar' }}
        run: |
          if [ "${{ github.event.inputs.branch }}" = "main" ]; then
            curl -X POST "${{ secrets.VERCEL_DEPLOY_CALENDAR_MAIN }}"
          elif [ "${{ github.event.inputs.branch }}" = "dev" ]; then
            curl -X POST "${{ secrets.VERCEL_DEPLOY_CALENDAR_DEV }}"
          elif [ "${{ github.event.inputs.branch }}" = "qa" ]; then
            curl -X POST "${{ secrets.VERCEL_DEPLOY_CALENDAR_QA }}"
          fi
