name: Manual Deploy to Vercel

on:
  workflow_dispatch:
    inputs:
      app:
        description: 'target (landing / calendar)'
        required: true
        type: choice
        options:
          - landing
          - calendar
      branch:
        description: 'branch (main/dev)'
        default: 'main'
        required: true
        type: choice
        options:
          - main
          - dev

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Deploy landing
        if: ${{ github.event.inputs.app == 'landing' }}
        run: |
          cd apps/landing
          npm ci
          npx vercel build --token=${{ secrets.VERCEL_TOKEN }}
          if [ "${{ github.event.inputs.branch }}" = "main" ]; then
            npx vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }} --prod
          else
            npx vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }}
          fi
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID_LANDING }}

      - name: Deploy calendar
        if: ${{ github.event.inputs.app == 'calendar' }}
        run: |
          cd apps/calendar
          npm ci
          npx vercel build --token=${{ secrets.VERCEL_TOKEN }}
          if [ "${{ github.event.inputs.branch }}" = "main" ]; then
            npx vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }} --prod
          else
            npx vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }}
          fi
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID_CALENDAR }}
